FORMAT: 1A
HOST: http://boilerpl8.me/

# boilerpl8

Boilerpl8 has a simple API to discover new recipes in your favorite cuisines and learn about the ingredients in your food.

## Search Collection [/api/search{?query,limit}]

### Search Database [GET]

+ Parameters
    + query - query string 
    + limit - number of items returned 

+ Response 200 (application/json)

        {
            "results": [
                {
                    "image": "http://cdn.foodfacts.com/images/products/", 
                    "link": "/ingredients/129056", 
                    "title": "Aloha Vinegar, Apple Cider", 
                    "type": "Ingredient"
                }, 
                {
                    "image": "https://spoonacular.com/recipeImages/turkey-apple-swedish-meatballs-286238.jpeg", 
                    "link": "/recipes/282", 
                    "title": "Turkey-Apple Swedish Meatballs", 
                    "type": "Recipe"
                }, 
                {
                    "image": "https://spoonacular.com/recipeImages/spanish-pork-with-apple-citrus-salsa-82349.jpg", 
                    "link": "/recipes/1561", 
                    "title": "Spanish Pork with Apple-Citrus Salsa", 
                    "type": "Recipe"
                }, 
                {
                    "image": "https://spoonacular.com/recipeImages/spanish-pork-with-apple-citrus-salsa-708221.jpg", 
                    "link": "/recipes/1562", 
                    "title": "Spanish Pork with Apple-Citrus Salsa", 
                    "type": "Recipe"
                }, 
                {
                    "image": "https://spoonacular.com/recipeImages/Curry-Turkey-Salad-with-Apples---Celery-539204.jpg", 
                    "link": "/recipes/1310", 
                    "title": "Curry Turkey Salad with Apples & Celery", 
                    "type": "Recipe"
                }
            ]
        }

## Cuisines Collection [/api/cuisines/]

### List Cuisines [GET]

+ Response 200 (application/json)

        {
            "cuisines": [
                {
                    "averageCalories": 300, 
                    "averageNumberOfIngredientsPerRecipe": 5, 
                    "continent": "North America", 
                    "id": 1, 
                    "numberOfRecipes": 1, 
                    "title": "American"
                }, {

                    "averageCalories": 270, 
                    "averageNumberOfIngredientsPerRecipe": 6, 
                    "continent": "Asia", 
                    "id": 25, 
                    "numberOfRecipes": 3, 
                    "title": "Chinese"
                }
            ]
        }
        
## Cuisine Information Collection [/api/cuisines/{cuisine_id}/]
### Get information for a cuisine [GET] 

+ Parameters
    + cuisine_id (number) - ID of the cuisine 

+ Response 200 (application/json)

        {
            "averageCalories": 300, 
            "averageNumberOfIngredientsPerRecipe": 5, 
            "continent": "North America", 
            "id": 1, 
            "numberOfRecipes": 1, 
            "title": "American"
        }
        
## Cuisine with Recipe Collection [/api/cuisines/{cuisine_id}/recipes/]
### Get information for a cuisine with list of related recipes [GET]

+ Parameters
    + cuisine_id (number) - ID of the cuisine

+ Response 200 (application/json)

        {
            "recipes": [
                {
                    "title": "GrilledCheese",
                    "readyInMinutes": 10,
                    "servings": 2,
                    "calories": 300,
                    "steps": "Heat pan on medium heat. Put cheese between two slices of bread. Cook both sides of the sandwich."
                }, 
                {
                    "title": "GrilledCheese",
                    "readyInMinutes": 10,
                    "servings": 2,
                    "calories": 300,
                    "steps": "Heat pan on medium heat. Put cheese between two slices of bread. Cook both sides of the sandwich."
                }
            ], 
            "cuisine": 
                {
                    "averageCalories": 300, 
                    "averageNumberOfIngredientsPerRecipe": 5, 
                    "continent": "North America", 
                    "id": 1, 
                    "numberOfRecipes": 1, 
                    "title": "American"   
                }
        }
    

     
## Recipe Collection [/api/recipes/]
### List Recipes [GET]

+ Response 200 (application/json)

        {
            "recipes": [
                {
                    "title": "GrilledCheese",
                    "readyInMinutes": 10,
                    "servings": 2,
                    "calories": 300,
                    "steps": "Heat pan on medium heat. Put cheese between two slices of bread. Cook both sides of the sandwich."
                }, 
                {
                    "title": "Pasta",
                    "readyInMinutes": 14,
                    "servings": 2,
                    "calories": 250,
                    "steps": "Boil water. Put pasta in the boiling water for 14 minutes. Strain and enjoy!"
                }
            ]
        }

        
## Recipe Information Collection [/api/recipes/{recipe_id}/]
### Get information for a recipe [GET]

+ Parameters
    + recipe_id (number) - ID of the recipe 


+ Response 200 (application/json)

        {
            "title": "GrilledCheese",
            "readyInMinutes": 10,
            "servings": 2,
            "calories": 300,
            "steps": "Heat pan on medium heat. Put cheese between two slices of bread. Cook both sides of the sandwich."
        }

## Recipe with Ingredients and Cuisine Collection [/api/recipes/{recipe_id}/ingredients/]
### Get information for a recipe, including a list of ingredients and type of cuisine [GET]


+ Parameters
    + recipe_id (number) - ID of the recipe
    
+ Response 200 (application/json)

        {
            "ingredients": [
                {
                    "brand": "Bread Inc", 
                    "category": "Bread", 
                    "id": 1, 
                    "imageURL": "https://static.pexels.com/photos/5802/bread-food-cooking.jpg", 
                    "serving_size": "1 slice", 
                    "title": "Bread", 
                    "total_weight": "3 oz"
                },                 
                {
                    "brand": "Cheese Inc", 
                    "category": "Dairy", 
                    "id": 89, 
                    "imageURL": "http://media.istockphoto.com/photos/cheese-picture-id510168428", 
                    "serving_size": "1 slice", 
                    "title": "Cheese", 
                    "total_weight": "1 oz"
                }, 
            ], 
            "recipe":
                {
                    "title": "GrilledCheese",
                    "readyInMinutes": 10,
                    "servings": 2,
                    "calories": 300,
                    "steps": "Heat pan on medium heat. Put cheese between two slices of bread. Cook both sides of the sandwich."
                },
            "cuisine": 
                {
                    
                }
        }
   
## Recipe with Ingredient Info and Cuisine Collection [/api/recipe/{recipe_id}/ingredientInfo/]
### Get information for a recipe, including a list of ingredients information and type of cuisine [GET]

+ Parameters
    + recipe_id (number) - ID of the recipe
    
+ Response 200 (application/json)

        {
            "cuisine": {
            "averageCalories": 133.355555555556, 
            "averageNumberOfIngredientsPerRecipe": 9.33333333333333, 
            "continent": "Europe", 
            "id": 59, 
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Europe_orthographic_Caucasus_Urals_boundary_%28with_borders%29.svg/537px-Europe_orthographic_Caucasus_Urals_boundary_%28with_borders%29.svg.png", 
            "numberOfRecipes": 45, 
            "title": "Italian"
          }, 
          "ingredients": [
            {
              "fullName": "4 egg whites", 
              "id": 15429, 
              "ingredient_id": 204785, 
              "name": "egg whites", 
              "recipe_id": 1494
            }, 
            {
              "fullName": "1 Large Eggplant, peeled and sliced into 1/4\" rounds", 
              "id": 15430, 
              "ingredient_id": 21572, 
              "name": "eggplant", 
              "recipe_id": 1494
            }, 
            {
              "fullName": "Fat Free Parmesan Cheese", 
              "id": 15431, 
              "ingredient_id": null, 
              "name": "fat free parmesan cheese", 
              "recipe_id": 1494
            }, 
            {
              "fullName": "2 C favorite tomato sauce (please make your own, it's so easy and so much yummier)", 
              "id": 15432, 
              "ingredient_id": 185246, 
              "name": "tomato sauce", 
              "recipe_id": 1494
            }
          ], 
          "recipe": {
            "calories": 151, 
            "cuisine_id": 59, 
            "id": 1494, 
            "imageURL": "https://spoonacular.com/recipeImages/17-Day-Diet-Eggplant-Parmesan-563407.jpg", 
            "numberOfSteps": 6, 
            "readyInMinutes": 120, 
            "servings": 2, 
            "steps": "Pre-heat oven to 400\u00b0F Mix Fat Free (shaker) Parmesan Cheese with a couple dashes, paprika and fresh ground parmesan cheese.Peel the eggplant and slice into 1/4\" thick rounds Whisk the egg whites until frothy Dip the eggplant slices into the egg whites until coated - lightly dip each side into the parmesan cheese mixture and lay on a vented broiler sheet Put in 400\u00b0F oven for 20 minutes, flip and bake another 10 minutes Serve topped with your homemade tomato sauce", 
            "title": "17 Day Diet Eggplant Parmesan"
          }
        }
        
## Ingredient Collection [/api/ingredients/]
### List Ingredients [GET]

+ Response 200 (application/json)

        {
            "ingredients": [
                {
                "brand": "Bread Inc", 
                "category": "Bread", 
                "id": 1, 
                "imageURL": "https://static.pexels.com/photos/5802/bread-food-cooking.jpg", 
                "serving_size": "1 slice", 
                "title": "Bread", 
                "total_weight": "3 oz"
                }, 
                {
                "brand": "Orange Inc", 
                "category": "Citrus", 
                "id": 45, 
                "imageURL": "https://static.pexels.com/photos/67867/orange-falling-water-splash-67867.jpeg", 
                "serving_size": "1 orange", 
                "title": "Orange", 
                "total_weight": "10 oz"
                }
            ]
        }

## Ingredient to Recipes Collection [/api/ingredients/{ingredient_id}/recipes/]
### Get recipes an ingredient is in [GET]        

+ Parameters
    + ingredient_id (number) - ID of the ingredient 
        
+ Response 200 (application/json)

        {
            "ingredient": {
            "brand": "Eggplant",
            "category": "Fruits / Nuts / Vegetables",
            "id": 21572,
            "imageURL": "http://cdn.foodfacts.com/images/products/21572.jpg",
            "serving_size": "1 Avg Eggplant",
            "title": "Eggplant",
            "total_weight": "1 Avg"
        },
        "recipes": [
            {
            "id": 198,
            "name": "West African Peanut Stew"
            },
            {
            "id": 1451,
            "name": "Eggplant Turkey Lasagna"
            },
            {
            "id": 1455,
            "name": "Eggplant Parmesan"
            },
            {
            "id": 1494,
            "name": "17 Day Diet Eggplant Parmesan"
            }
        ]
        }

## Ingredient Information Collection [/api/ingredients/{ingredient_id}/]
### Get information for an ingredient [GET]

+ Parameters
    + ingredient_id (number) - ID of the ingredient 

+ Response 200 (application/json)

        {
          "brand": "Bread Inc", 
          "category": "Bread", 
          "id": 1, 
          "imageURL": "https://static.pexels.com/photos/5802/bread-food-cooking.jpg", 
          "serving_size": "1 slice", 
          "title": "Bread", 
          "total_weight": "3 oz"
        }